### ISSUE TITLE
5.3 사전 훈련된 컨브넷 사용하기 관련 질문 있습니다.

### ISSUE THREAD

**Issue by actruce** [rickiepark/deep-learning-with-python-notebooks#1]
특성 추출하기에서,

데이터 증식을 사용하는 경우와 사용하지 않는 경우에 End-to-End 로 학습시킬지가 결정이 되는거 같은데, 정확히 이해를 못하였습니다.

데이터 증식을 사용하는 경우 (ImageDataGenerator 를 사용하는 경우), 왜 학습된 VGG16 이후에 그대로 conv_base.predict() 를 사용하지 못하고 End-to-End 학습을 해야 하는지요?

사용하는 함수도 model.fit 과 model.fit_generator 로 다른데 이 부분도 같이 설명해 주시면 감사하겠습니다.

**Comment by rickiepark** [comment]
안녕하세요.
데이터 증식을 사용하지 않으면 훈련 세트를 conv_base에 통과시켜 특성을 뽑아 놓고 모델을 훈련하는 것이 효율적입니다. 데이터 증식은 반복마다 동적으로 새로운 이미지를 만들기 때문에 미리 특성을 뽑아 놓으려면 훈련 세트 개수만큼이 아니라 훈련 세트 x 에포크 횟수만큼 훈련 세트가 늘어나게 됩니다. 더욱이 케라스 콜백을 사용하여 조기종료를 사용하려면 얼만큼의 에포크만큼 수행할지도 사전에 정의하기 어렵습니다. 이런 이유들로 데이터 증식을 사용하는 경우에는 end-to-end로 수행하는 것이 일반적입니다.
fit 메서드와 fit_generator의 차이는 훈련 세트 매개변수로 파이썬 제너레이터를 사용하는 것입니다. 파이썬 제너레이터는 데이터가 필요할 때까지 연산을 지연시키는 효과가 있습니다. 주로 대량의 데이터를 한 번에 메모리에 올리지 않기 위해 많이 사용하죠. 제너레이터에 관한 설명은 제 블로그를 참고해 주세요(https://bit.ly/2KGrQxk).
더 궁금한 점이 있다면 알려 주세요. 감사합니다. :)

**Comment by rickiepark** [comment]
이 이슈는 종결하겠습니다. 궁금한 점 있으면 다른 이슈를 올려 주세요. :)
