### ISSUE TITLE
[5.2-using-convnets...] flow 는 언제 사용하는건가요 ? +alpha

### ISSUE THREAD

**Issue by jongseo-park** [rickiepark/deep-learning-with-python-notebooks#3]
증식된 이미지 샘플을 살펴보는 부분 (In [20]: ..) 에서

마지막에 flow 를 이용해서 이미지를 4 개 추출하여 보여주셨는데

flow 는 언제 사용하는건지 궁금합니다.

flow_from_directory 는 디렉토리명에 따라 달리 레이블을 지정해주는 듯한데요,

flow 는 단순히 이렇게 이미지를 볼때 사용하라고 만든것은 아닐 것 같아서요.

- - -

그리고, 과대적합을 해결하기 위해 여러 기법을 사용하는 것을 배웠는데

예를들어 과대적합이 epoch 4 번째에 시작된다고 하면,

epoch = 3 으로 제한하는 것과,

여러 기법을 통해 더 많은 수의 epoch 까지 과대적합이 일어나지 않게 하는 것 중 

왜 후자의 방법을 택해야 하는지 잘 모르겠습니다.
,
epoch 가 늘어날수록 가중치를 수정할 기회가 많아져서 정확도가 증가하는건가요 ?

**Comment by rickiepark** [comment]
안녕하세요. flow() 메서드는 메모리에 로드된 데이터에서 배치를 생성합니다. 다음 주소를 참고하세요.
https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator#flow
과대적합을 해결하는 방법은 문제에 따라 다릅니다. 만약 에포크 3에서 중지하는 것으로 모델 성능이 만족스럽지 않다면 다른 기법으로 과대적합이 늦게 일어나도록 지연하는 것이 좋습니다.
감사합니다.
